export const REPORTGENERATORFIELDS = {
    id: 'شناسه یکتا',
    niazsanjiYear: 'سال نیازسنجی',
    niazSanjiSource: 'منبع نیازسنجی',
    priceCost: 'سرمایه مصوب شده(ریال)',
    description: 'توضیحات بیشتر',
    createUserLogin: 'کاربر ایجاد کننده',
    createDate: 'تاریخ ایجاد',
    modifyUserLogin: 'کاربر ویرایش کننده',
    modifyDate: 'تاریخ ویرایش شده',
    archived: 'آرشیو شده؟',
    archivedUserLogin: 'آرشیو شده توسط',
    archivedDate: 'تاریخ آرشیو',
    statusMeaning: 'وضعیت',
    runMonthPersian: 'ماه اجرا',
    planningRunMonthPersian: 'ماه برنامه ریزی',
    finalizeCost: 'سرمایه گذاری صرف شده',
    hasImportantMessage: 'پیغام مهم؟',
    'restrictions.many.title': 'عناوین محدودیت ها',
    restrictionDescription: 'توضیح محدودیت',
    goalsText: 'اهداف(نتایج مورد انتظار-اهداف کلی، جزئی، رفتاری و یادگیری و ...)',
    prerequisite: 'پیش نیاز',
    priority: 'اولویت بندی',
    effectivenessPhaseAverage: 'میانگین اثربخشی',
    effectivenessPhaseGrade: 'گرید اثربخشی',
    selectedEffectivenessPhaseLevelTitle: 'سطح انتخابی',
    currentEffectivenessPhaseLevelTitle: 'سطح جاری',
    lastEffectivenessPhaseFinishPersian: 'تاریخ تکمیل آخرین سطح',
    'finalNiazsanjiReportPeople.Many.personFullName': 'افراد (فرد) شرکت کننده در دوره',
    'designAndPlannings.one.directCost': 'سرمایه گذاری های مستقیم',
    'designAndPlannings.one.directCostDescription': 'تشریح سرمایه گذاری های مستقیم',
    'designAndPlannings.one.undirectCost': 'سرمایه گذاری های غیرمستقیم',
    'designAndPlannings.one.undirectCostDescription': 'تشریح سرمایه گذاری های غیرمستقیم',
    'designAndPlannings.one.finished': 'برنامه ریزی تایید نهایی شده؟',
    'designAndPlannings.one.finishedDate': 'تاریخ نهایی شدن برنامه ریزی',
    'runPhases.one.finalizeCost': 'سرمایه گذاری صرف شده(ریال)',
    'runPhases.one.done': 'فاز اجرا نهایی شده؟',
    'runPhases.one.doneDate': 'تاریخ نهایی شدن فاز اجرا',
    'runPhases.one.finishDate': 'تاریخ دقیق برگزاری دوره',
    teacherFullName: 'استاد',
    niazsanjiInputTitle: 'ورودی نیازسنجی',
    courseTypeTitle: 'نوع دوره',
    organizationChartTitle: 'عنوان چارت سازمانی',
    organizationChartFullTitle: 'عنوان کامل چارت سازمانی',
    organizationChartRootTitle: 'گروه',
    educationalModuleTitle: 'عنوان پودمان آموزشی',
    educationalModuleCode: 'کد پودمان آموزشی',
    educationalModuleLevelTitle: 'سطح پودمان آموزشی',
    educationalModuleLearningTimeTheorical: 'مدت پودمان نظری',
    educationalModuleLearningTimePractical: 'مدت پودمان عملی',
    educationalModuleTotalTime: 'مدت کل پودمان',
    mahiatCourseTitle: 'ماهیت دوره',
    teachingApproachTitle: 'روش های آموزش'
};
